name: Email Jobs

on: 
  schedule: 
    - cron: '0 8 * * *'     
  workflow_dispatch:

jobs:
  build:
    name: Run Email User Jobs Script
    runs-on: ubuntu-latest
    env: 
      ADZUNA_ID: ${{ secrets.ADZUNA_ID }}
      ADZUNA_KEY: ${{ secrets.ADZUNA_KEY }}
      TO_EMAIL: ${{ secrets.TO_EMAIL }}
      FROM_EMAIL: ${{ secrets.FROM_EMAIL }}
      FROM_PASSWORD: ${{ secrets.FROM_PASSWORD }}
      APP_PASSWORD: ${{ secrets.APP_PASSWORD }}
      SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}

    steps:
    - name: Setup Environment 
      uses: ./.github/workflows/setup.yaml

    - name: Run Script
      run: python3 ./src/scripts/send_emails.py



