name: Run Tests

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test1:
    name: Run Event Logging Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo         #gets repo code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: ./.github/actions/setup_env
      
      - name: Run Test
        runs: pytest ./tests/test_event_logging.py
  
  test2:
    name: Run Fetcher Class Tests
    runs-on: ubuntu_latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      
      - name: Setup Python
        uses: ./.github/actions/setup_env
      
      - name: Run Test
        runs: pytest ./tests/test_fetcher_class.py
  
  test3:
    name: Run Job Mappings Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      
      - name: Setup Python
        uses: ./.github/actions/setup_env

      - name: Run Test
        runs: pytest ./tests/test_job_mappings.py

  test4:
    name: Run Database Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      
      - name: Setup Python
        uses: ./.github/actions/setup_env

      - name: Run Test
        runs: pytest ./tests/test_query.py 