name: Run Tests

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test1:
    name: Run Database Tests
    runs-on: ubuntu-latest

    steps:
      - name: Setup Python
        uses: ./.github/actions/setup_env